version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: git config user.email "2326220@163.com"
            - run: git config user.name "twomeetings"
            - run: npm run deploy
workflows:
    build-and-test:
      jobs:
        - build-and-deploy